dependencies:
- condition: activiti-cloud-modeling.enabled,modeling.enabled
  name: activiti-cloud-modeling
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.6.0
- alias: activiti-cloud-notifications
  name: activiti-cloud-notifications-graphql
  repository: https://introproventures.github.io/activiti-cloud-helm-charts/
  version: 1.0.7
- name: activiti-irt-activity-connector
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: activiti-irt-activity-rb
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
- name: application
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.6.1
- name: demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.6.0
